version: '3'
services:
    backend:
        build: 
            context: .
            dockerfile: dockerfile.dev
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "3003:3003"           
networks:
    default:
        external: true
        name: tuxtum
volumes:
    db_data:
